type: object
properties:
  manifest:
    type: object
    properties:
      allowBackup:
        type: string
      icon:
        type: string
      label:
        type: string
      roundIcon:
        type: string
      supportsRtl:
        type: string
      theme:
        type: string
      activity:
        type: object
        properties:
          name:
            type: string
          label:
            type: string
          intentFilters:
            type: object
            additionalProperties:
              type: object
              properties:
                type:
                  type: string
                  enum:
                    - action
                    - category
                name:
                  type: string
